---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: test-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: script
    scripts:
    - netbird_repo.sh # example: run files/scripts/netbird_repo.sh
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - freeipa-client
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: rpm-ostree
    install:
    - netbird
  - type: systemd
    system:
      units:
      - name: "netbird.service"
        # Create a drop-in file to be placed in /etc/systemd/system/netbird.service.d/
        # The 50-socket-permissions.conf is the filename for the drop-in.
        dropins:
          - name: "50-socket-permissions.conf"
            # The content for the drop-in file
            content: |
              [Service]
              # Ensure the socket directory is created with correct permissions
              RuntimeDirectory=netbird
              RuntimeDirectoryMode=0755
              
              # Set the group ownership of the socket
              SocketGroup=wheel # e.g., 'netbird' or 'wheel'
  
              # Ensure the correct permissions are applied to the socket file
              # 0660 allows read/write for the owner (root) and the specified group
              UMask=0007 # This sets the inverse of the desired permissions (0660)
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.libreoffice.LibreOffice
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
